repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check src
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: ruff-format-check
        name: ruff format check
        entry: uv run ruff format --check src
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
