repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check src
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: import-check
        name: import gateway.main
        entry: uv run python -c "import gateway.main"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
